import express from "express";
import { fetchCategory, saveInBulk, save, deletCategory, getCategory } from "../controller/category.controller.js";
import { auth } from "../middleware/auth.js";
const router = express.Router();
router.post("/save-in-bulk",auth,saveInBulk);
router.get("/list",auth,fetchCategory);
router.post("/save",auth,save);
router.delete("/:id",auth,deletCategory);
router.get("/:id",auth,getCategory);
export default router;